### ISSUE TITLE
Fix problems with some SSL certificates preventing application from fetching blog posts.

### ISSUE THREAD

**Issue by tdziurko** [jvm-bloggers/jvm-bloggers#334]
```
2017-03-08 10:59:51.688  WARN 14316 --- [pool-3-thread-1] c.j.core.rss.SyndFeedProducer            : Error during fetching RSS https://softwaremill.com/feed.xml url

javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_112]
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154) ~[na:1.8.0_112]
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023) ~[na:1.8.0_112]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125) ~[na:1.8.0_112]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375) ~[na:1.8.0_112]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403) ~[na:1.8.0_112]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387) ~[na:1.8.0_112]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[na:1.8.0_112]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[na:1.8.0_112]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546) ~[na:1.8.0_112]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[na:1.8.0_112]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_112]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338) ~[na:1.8.0_112]
	at com.jvm_bloggers.core.data_fetching.http.ProtocolSwitchingAwareConnectionRedirectHandler.handle(ProtocolSwitchingAwareConnectionRedirectHandler.java:66) ~[main/:na]
	at com.jvm_bloggers.core.rss.SyndFeedProducer.createFor(SyndFeedProducer.java:38) [main/:na]
	at com.jvm_bloggers.core.rss.SyndFeedProducer.validUrlFromRss(SyndFeedProducer.java:51) [main/:na]
	at com.jvm_bloggers.core.data_fetching.blogs.BloggersDataUpdater.extractValidBlogUrlFromFeed(BloggersDataUpdater.java:66) [main/:na]
```

**Comment by goostleek** [comment]
Tomek, could you provide more logs for this, please? Wider context would be appreciated, eg. which blogs (urls) are causing this.

**Comment by tdziurko** [comment]
@goostleek Stacktrace updated, exception is thrown in both adding new blog and checkins rss for latest entries.

**Comment by goostleek** [comment]
Thx. In the mean time I recalled that I have solved similar problem some time ago. This is related to (J)ava (C)ryptography (E)xtensions distributed in JVM which is [limited in encryption strength](http://docs.oracle.com/javase/8/docs/technotes/guides/security/SunProviders.html#importlimits) according to US law for exported technologies. So the server we are trying to fetch data from is stronger than 128 bit encryption that cannot be properly handled by the JVM our application is running on according to US regulations. Fortunately [the solution](http://stackoverflow.com/a/38264878/2443502) for that is pretty straightforward.

**Comment by goostleek** [comment]
@tdziurko I can handle that if you don't mind. I will tweak out docker build to include necessary fixes.

**Comment by tdziurko** [comment]
But this is happening also on my local machine with latest JDK8 with added JCE. And it happens only with my company's blog :)

It might be related to https://www.sslshopper.com/ssl-checker.html#hostname=softwaremill.com (we have a new webpage for some time now) and maybe this SHA-1 somewhere along the chain is causing problems.

**Comment by tdziurko** [comment]
More debug logs:

    ForkJoinPool.commonPool-worker-6, WRITE: TLSv1.2 Handshake, length = X
    [Raw write]: length = Y
    (...)
    ForkJoinPool.commonPool-worker-6, READ: TLSv1.2 Alert, length = 2
    ForkJoinPool.commonPool-worker-6, RECV TLSv1.2 ALERT:  fatal, handshake_failure
    ForkJoinPool.commonPool-worker-6, called closeSocket()
    ForkJoinPool.commonPool-worker-6, handling exception: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

**Comment by petervalencic** [comment]
I have the same Error: 
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
at com.sun.net.ssl.internal.ssl.Alerts.getSSLException(Alerts.java)
at com.sun.net.ssl.internal.ssl.Alerts.getSSLException(Alerts.java)
at com.sun.net.ssl.internal.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java)
at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java)
at com.sun.net.ssl.internal.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java)
at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java)
at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java)
at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java)
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java)
at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
at FursTestBaza.Test(FursTestBaza:92)

When try to make a SSL connection from oracle database with Java to some remote server over https.

**Comment by tdziurko** [comment]
Hi. 
1. You need JDK 8
2. Probably you need to have JCE (Java Cryptography Extension) enabled - [link](http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html)

**Comment by goostleek** [comment]
What java version do you have?
https://stackoverflow.com/a/46883499/2443502
>According to [JDK-8170157](https://bugs.openjdk.java.net/browse/JDK-8170157), since JDK 6u181, 7u171, 8u161, 9b148 unlimited cryptographic policy is enabled by default. So all you have to do is just upgrade to the corresponding baseline.

**Comment by TomaszSzt** [comment]
Just for Your information: the same happens with an attempt to build GITBLIT which REQUIRES JDK 1.7 and with JDK1.7.0_02. Since JDK 1.7 requires ANT 1.9.... You know what, I am stuck. Efficiently it is NOT possible to build this program using previously working tool chain.

        at org.moxie.Repository.downloadPrefixIndex(Repository.java:248)
        at org.moxie.Solver.retrievePrefixIndex(Solver.java:686)
        at org.moxie.Solver.updateRepositoryMetadata(Solver.java:201)
        at org.moxie.Build.setup(Build.java:156)
        at org.moxie.ant.MxInit.execute(MxInit.java:137)
        ... 16 more
Caused by: javax.net.ssl.SSLException: Received fatal alert: protocol_version
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
        at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1943)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1059)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1294)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1321)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1305)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:523)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1296)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
        at org.moxie.Repository.getConnection(Repository.java:549)
        at org.moxie.Repository.download(Repository.java:571)
        at org.moxie.Repository.downloadPrefixIndex(Repository.java:227)
        ... 20 more
