### ISSUE TITLE
missing entries

### ISSUE THREAD

**Issue by Gvaireth** [jvm-bloggers/jvm-bloggers#343]
In issue 80 from 24.03.2017, an entry from 23.03.2017 from https://howtotrainyourjava.com/ was omitted.

**Comment by tdziurko** [comment]
This has something to do with SSL connection, currently `SyndFeedProducer` tries to connect two times:
 - 1st approach with a standard JCE enabled (see parent docker image)
 - 2nd approach as a fallback with a connection that *should* accept all SSL certificates (self-signed, free ones, etc.)

But apparently something is not working when it comes to your blog. Below logs, I will try to investigate it deeper, but this is not a trivial problem:


    2017-04-01 19:01:49.554  WARN 1 --- [pool-3-thread-1] c.j.core.rss.SyndFeedProducer            : Error during fetching RSS without https check for https://howtotrainyourjava.com/feed/ url
    
    javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_92]
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949) ~[na:1.8.0_92]
    at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302) ~[na:1.8.0_92]
    at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296) ~[na:1.8.0_92]
    at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509) ~[na:1.8.0_92]
    at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[na:1.8.0_92]
    at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979) ~[na:1.8.0_92]
    at sun.security.ssl.Handshaker.process_record(Handshaker.java:914) ~[na:1.8.0_92]
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062) ~[na:1.8.0_92]
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375) ~[na:1.8.0_92]
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403) ~[na:1.8.0_92]
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387) ~[na:1.8.0_92]
    at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[na:1.8.0_92]
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[na:1.8.0_92]
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513) ~[na:1.8.0_92]
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[na:1.8.0_92]
    at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_92]
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338) ~[na:1.8.0_92]
    at com.jvm_bloggers.core.data_fetching.http.ProtocolSwitchingAwareConnectionRedirectHandler.handle(ProtocolSwitchingAwareConnectionRedirectHandler.java:66) ~[classes!/:na]
    at com.jvm_bloggers.core.rss.SyndFeedProducer.createWithoutSslVerification(SyndFeedProducer.java:82) [classes!/:na]
    at com.jvm_bloggers.core.rss.SyndFeedProducer.createFor(SyndFeedProducer.java:47) [classes!/:na]
    at com.jvm_bloggers.core.rss.SyndFeedProducer.validUrlFromRss(SyndFeedProducer.java:51) [classes!/:na]
    at com.jvm_bloggers.core.data_fetching.blogs.BloggersDataUpdater.extractValidBlogUrlFromFeed(BloggersDataUpdater.java:65) [classes!/:na]
    at com.jvm_bloggers.core.data_fetching.blogs.BloggersDataUpdater.updateBloggerIfThereAreAnyChanges(BloggersDataUpdater.java:45) [classes!/:na]
    at com.jvm_bloggers.core.data_fetching.blogs.BloggersDataUpdater.lambda$updateSingleEntry$0(BloggersDataUpdater.java:39) [classes!/:na]
    at java.util.Optional.map(Optional.java:215) ~[na:1.8.0_92]
    at com.jvm_bloggers.core.data_fetching.blogs.BloggersDataUpdater.updateSingleEntry(BloggersDataUpdater.java:38) [classes!/:na]
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_92]
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_92]
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_92]
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_92]
    at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[na:1.8.0_92]
    at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[na:1.8.0_92]
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_92]
    at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1870) ~[na:1.8.0_92]
    at java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:2467) ~[na:1.8.0_92]
    at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:324) ~[na:1.8.0_92]
    at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:405) ~[na:1.8.0_92]
    at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734) ~[na:1.8.0_92]
    at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) ~[na:1.8.0_92]
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) ~[na:1.8.0_92]
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[na:1.8.0_92]
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_92]
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:496) ~[na:1.8.0_92]
    at com.jvm_bloggers.core.data_fetching.blogs.BloggersDataUpdater.updateData(BloggersDataUpdater.java:32) [classes!/:na]
    at com.jvm_bloggers.core.data_fetching.blogs.BloggersDataFetcher.refreshBloggersDataFor(BloggersDataFetcher.java:85) ~[classes!/:na]
    at com.jvm_bloggers.core.data_fetching.blogs.BloggersDataFetcher.startFetchingProcess(BloggersDataFetcher.java:69) ~[classes!/:na]
    at com.jvm_bloggers.core.data_fetching.blogs.PreventConcurrentExecutionSafeguard.preventConcurrentExecution(PreventConcurrentExecutionSafeguard.java:19) ~[classes!/:na]
    at com.jvm_bloggers.core.data_fetching.blogs.BloggersDataFetcher.refreshData(BloggersDataFetcher.java:60) ~[classes!/:na]
    at com.jvm_bloggers.core.data_fetching.blogs.BloggersDataFetcher$$FastClassBySpringCGLIB$$caf3981.invoke(<generated>) ~[classes!/:na]
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
    at com.jvm_bloggers.core.data_fetching.blogs.BloggersDataFetcher$$EnhancerBySpringCGLIB$$a6849813.refreshData(<generated>) ~[classes!/:na]
    at com.jvm_bloggers.core.data_fetching.blogs.BloggersDataFetchingScheduler.fetchBloggersData(BloggersDataFetchingScheduler.java:19) ~[classes!/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
    at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
    at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
    at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_92]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_92]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_92]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_92]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_92]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_92]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_92]
    Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387) ~[na:1.8.0_92]
    at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292) ~[na:1.8.0_92]
    at sun.security.validator.Validator.validate(Validator.java:260) ~[na:1.8.0_92]
    at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[na:1.8.0_92]
    at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[na:1.8.0_92]
    at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[na:1.8.0_92]
    at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491) ~[na:1.8.0_92]
    ... 63 common frames omitted
    Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141) ~[na:1.8.0_92]
    at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126) ~[na:1.8.0_92]
    at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280) ~[na:1.8.0_92]
    at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382) ~[na:1.8.0_92]
    ... 69 common frames omitted

**Comment by airborn** [comment]
Maybe this is the point at which we should switch away from low level http api?

**Comment by tdziurko** [comment]
Care to elaborate more? :)

**Comment by airborn** [comment]
Just wondering if switching to i.e. Jersey Client would simplify this problem. It would for sure simplify code in general and allow for redesign of current implementation that lacks proper testing (please recall recent discussion on Slack channel saying that `ProtocolSwitchingAwareConnectionRedirectHandlerSpec` randomly fails for some people)

**Comment by tdziurko** [comment]
Yeah, it would make code simpler though I don't think it would allow us to get rid of occasional SSL problems with some blogs.

**Comment by Gvaireth** [comment]
Same issue this week...

**Comment by tdziurko** [comment]
Fix is now live on production, your last four posts that were missing are now parsed and included in the next newsletter.
