### ISSUE TITLE
Exception when sending test email from admin panel

### ISSUE THREAD

**Issue by tdziurko** [jvm-bloggers/jvm-bloggers#393]
Stacktrace:

    2017-06-28 10:39:07.245 ERROR 1 --- [io-8080-exec-26] o.apache.wicket.DefaultExceptionMapper   : 
    Unexpected error occurred
    java.lang.NullPointerException: null
	at com.jvm_bloggers.frontend.admin_area.mailing.MailingPageRequestHandler.sendTestEmail(MailingPageRequestHandler.java:27) ~[classes!/:na]
	at WICKET_com.jvm_bloggers.frontend.admin_area.mailing.MailingPageRequestHandler$$EnhancerByCGLIB$$8aaff835.sendTestEmail(<generated>) ~[classes!/:na]
	at com.jvm_bloggers.frontend.admin_area.mailing.MailingPage$5.onSubmit(MailingPage.java:170) ~[classes!/:na]
	at org.apache.wicket.ajax.markup.html.form.AjaxButton$1.onSubmit(AjaxButton.java:113) ~[wicket-core-8.0.0-M6.jar!/:8.0.0-M6]
	at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior$AjaxFormSubmitter.onSubmit(AjaxFormSubmitBehavior.java:220) ~[wicket-core-8.0.0-M6.jar!/:8.0.0-M6]
	at org.apache.wicket.markup.html.form.Form.delegateSubmit(Form.java:1248) ~[wicket-core-8.0.0-M6.jar!/:8.0.0-M6]

**Comment by tdziurko** [comment]
Fixed by #d6fc86ecbdf0da8198d58dcc7161d5eaa9958401

@airborn  I couldn't reproduce it locally, but Wicket serializer seems to have problems with injecting Spring beans to @SpringBean annotated objects when there is no no-args constructor.
