### ISSUE TITLE
Issue, java.

### ISSUE THREAD

**Issue by Pajikos08** [jvm-bloggers/jvm-bloggers#674]
Please somebody fix. It happens when I load fabric api loader.
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at java.net.URL.openStream(URL.java:1038)
	at net.fabricmc.installer.util.Utils.urlReader(Utils.java:93)
	at net.fabricmc.installer.util.Utils.readTextFile(Utils.java:97)
	at net.fabricmc.installer.util.MetaHandler.load(MetaHandler.java:39)
	at net.fabricmc.installer.InstallerGui.<init>(InstallerGui.java:43)
	at net.fabricmc.installer.InstallerGui.start(InstallerGui.java:62)
	at net.fabricmc.installer.Main.main(Main.java:60)

**Comment by Pajikos08** [comment]
fixed
